version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    networks:
      - pgnetwork
    volumes: 
      - pgdata:/var/lib/postgresql

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file:
      - docker.env
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge

volumes:
  pgdata: